### ISSUE TITLE
Using fast-classpath-scanner in Maven plugin

### ISSUE THREAD

**Issue by vojtechhabarta** [lukehutch/fast-classpath-scanner#124] opened 2017-06-14 07:19 UTC
I am developing Maven plugin ([typescript-generator](https://github.com/vojtechhabarta/typescript-generator)) which is processing classes using reflection and I am using fast-classpath-scanner to get list of class names. It works well but now there is some issue when multi-module Maven project is built in parallel (reported here https://github.com/vojtechhabarta/typescript-generator/issues/142). In this case we get some class name from fast-classpath-scanner which we are not able to load using context class loader.

What I am doing now is:
- get "CompileClasspath" of the current Maven module
- create class loader `classLoader = new URLClassLoader(CompileClasspath, Thread.currentThread().getContextClassLoader())`
- set it as context classloader `Thread.currentThread().setContextClassLoader(classLoader)`
- get list of class names `new FastClasspathScanner().scan().getNamesOfClassesWithAnnotation()`
- and then I use `Thread.currentThread().getContextClassLoader().loadClass()` which sometimes fails

I really don't know what Maven is doing with classloaders especially in parallel builds but problematic class is from another module which is not in transitive dependencies of current module.

Should I use `FastClasspathScanner.overrideClassLoaders()` and pass it my context classloader?
It seams that my context classloader has "correct" list of classes so probably using `FastClasspathScanner.findBestClassLoader()` or letting fast-classpath-scanner to load classes is not right solution.

What do you think?

**Comment by lukehutch** [comment] 2017-06-14 08:31
@vojtechhabarta Oh man, this issue keeps coming up in all sorts of strange forms, and it's very hard to fix in a universal way...

I just checked in a fix for another problem earlier today (#37) -- the change is in git master, but not yet released. Can you please try the git master version to see if it fixes the problem?

If it doesn't fix the problem, I would appreciate it if you could please test versions 2.0.10, 2.0.11, 2.0.21 and 2.0.22, since there were a couple of changes between .10 and .11, and between .21 and .22, that may impact your situation.

**Comment by lukehutch** [comment] 2017-06-14 08:40
PS on your other questions -- hopefully the latest commit will make it so that `FastClasspathScanner.overrideClassLoaders()` is not needed. It's actually more dicey than I had anticipated to override the classloaders, because it is possible to easily end up in a situation where you load classes more than once into different classloaders, or the loaded class is not the same as the scanned class (when a class is defined more than once in the classpath).

**Comment by lukehutch** [comment] 2017-06-14 08:44
@vojtechhabarta I just noticed from the bug report you linked that you are calling `Class.loadClass()` yourself -- this is not the recommended way to do this. FastClasspathScanner keeps track of which ClassLoader should be used to load a class, and (as of the most recent commit) does so on a per-class basis. The code you want to call is `List<Class<?>> ScanResult#classNamesToClassRefs(List<String> classNames)` -- or use `MatchProcessors` instead ("Mechanism 1").

**Comment by lukehutch** [comment] 2017-06-14 09:06
I also just added `ScanResult#classNameToClassRef(className)`, which may be called for loading individual classes the optimal way.

**Comment by vojtechhabarta** [comment] 2017-06-15 20:58
@lukehutch thanks for your prompt response. I did some experiments on our multi-module maven project but I wasn't successful to reproduce the problem.

@sayresVT it would be helpful if you could try different fast-classpath-scanner versions (as @lukehutch suggested) but this would require using custom typescript-generator build and I understand this is not easy thing to do on your CI server.

@lukehutch I understand that it is recommended to let FastClasspathScanner load classes but in this case I prefer to use just classloader created from compile dependencies of the module. This seams to work correctly and doesn't have extra classes. I think it is better to ignore problematic class than try to load it using FastClasspathScanner and process it.

In any case I will upgrade fast-classpath-scanner to latest release (and then again when your latest commits get into some release). I will also change how class loading errors are handled (log the problem and continue) and I will also add switch for verbose output and we will see.

**Comment by vojtechhabarta** [comment] 2017-06-16 10:49
I just noticed that 2.0.22 and 2.2.0 releases are not in maven central repository. Do you plan to publish them?

**Comment by lukehutch** [comment] 2017-06-16 15:05
Oh, a recent user-submitted change to the Maven setup must have broken the Maven release plug in (it has happened before -- it's quite brittle). I'll see what I can do to fix that, although I don't have a lot of Maven expertise!

**Comment by lukehutch** [comment] 2017-06-16 17:06
@vojtechhabarta version 2.2.1 was released with the Maven fix, it should be in Maven Central soon (and is already in Sonatype). Please try this release instead of 2.0.22 or 2.2.0. Thanks!

**Comment by vojtechhabarta** [comment] 2017-06-16 21:26
Thanks for quick fix. You are really fast - not only your classpath scanner :wink:.
Thanks also for good explanation of class loading. I agree with it but I thing we are still talking about different things.

First of all _I had to create class loader_. 
I only have bunch of jars and directories which are not accessible through any class loader. So I create one and here I think starts the discussion. The question is how to use this class loader (or maybe what should be its parent).

When I run typescript-generator-maven-plugin with FCS in verbose mode I see 3 class loaders in log where FCS tries to find classpath elements:

```
---- Finding classpath elements in ClassLoader sun.misc.Launcher$AppClassLoader@55f96302
---- Finding classpath elements in ClassLoader ClassRealm[plugin>cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.25-SNAPSHOT, parent: sun.misc.Launcher$AppClassLoader@55f96302]
---- Finding classpath elements in ClassLoader TsGenURLClassLoader{myproject, parent: ClassRealm[plugin>cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.25-SNAPSHOT, parent: sun.misc.Launcher$AppClassLoader@55f96302]}
```

Among them only TsGenURLClassLoader has classes which are "interesting" for typescript-generator (though classes from other class loaders may be needed when loading those "interesting" classes).

So I tried to use `.overrideClassLoaders(TsGenURLClassLoader)` and then there were 2 class loaders which is still more than what I wanted.

```
---- Finding classpath elements in ClassLoader ClassRealm[plugin>cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.25-SNAPSHOT, parent: sun.misc.Launcher$AppClassLoader@55f96302]
---- Finding classpath elements in ClassLoader TsGenURLClassLoader{provisioning-service, parent: ClassRealm[plugin>cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.25-SNAPSHOT, parent: sun.misc.Launcher$AppClassLoader@55f96302]}
```

Now I am using `.overrideClasspath(myURLs)` which seems to do exactly what I wanted.

So that is the list of class _names_. Then I use my class loader to load those classes. I think this is also correct because my class loader has proper parent. Log from FCS confirms this.

Does this make sense now?

I will finalize changes and make release probably next week.

**Comment by lukehutch** [comment] 2017-06-17 19:51
@vojtechhabarta You're right, parent classloaders should not be added to the list to scan, I thought I had removed the code that automatically added parent classloaders long ago (parent classloaders are already called automatically as needed). I just checked in a fix for this. You should now only see one classloader in each case.

I don't recommend calling `.overrideClasspath()`, because the classpath may differ from the classpath of the classloaders, which can lead to some of the problems of unpredictability that I described in previous comments. I will need to remove this in future -- scanning should always be driven by classloaders (which can provide classpath elements), not by the classpath itself (which we can only rely on the context classloader to handle, and that only works reliably if the specified classpath is exactly the same as the context classloader's classpath, which defeats the purpose of being able to specify an override classpath).

However, `.overrideClassloaders()` can always be supported, and should work for your particular usecase.

Can you please verify if the parallel maven build issue is solved in v2.2.1?

**Comment by lukehutch** [comment] 2017-06-17 20:07
I just thought through the previous change, and actually, I need to revert it -- there was a reason I iterate through all the parent classloaders: sometimes people need to scan the classpath elements provided by parent classloaders, such as the system jars. Classpath elements or their contents are skipped if they don't meet whitelist criteria.

You should see higher up in the log that only one classloader is identified in each case. However, during the actual scanning, you will see `Finding classpath elements in ClassLoader` lines for the parent classloaders too. This is intentional.

**Comment by lukehutch** [comment] 2017-06-27 01:35
@vojtechhabarta I'm going to close this, since I think the issue is solved; please open another bug if you still see issues.

**Closed by lukehutch** 2017-06-27 01:35 UTC

**Comment by vojtechhabarta** [comment] 2017-07-12 09:21
@lukehutch it seems that issue https://github.com/vojtechhabarta/typescript-generator/issues/142 is resolved.
Thanks for all your support.

**Comment by lukehutch** [comment] 2017-07-13 06:38
@vojtechhabarta Thanks for closing the loop. I'm glad it's working for you now!
