### ISSUE TITLE
matchClassesWithAnnotation() does not match anything (1.9.11)

### ISSUE THREAD

**Issue by moldowan** [lukehutch/fast-classpath-scanner#39] opened 2016-01-04 13:46 UTC
In 1.9.11, ```FastClasspathScanner.matchClassesWithAnnotation(Class<?>, ClassAnnotationMatchProcessor)``` does not seem to match anything anymore. This is probably caused by #30.

I have different usages of this method and all are fine in 1.9.9 but they fail to find anything with 1.9.11+:
- finding interfaces annotated with ```javax.jws.WebService```
- finding concrete classes annotated with ```javax.persistence.Entity```
- finding concrete classes annotated with ```javax.xml.bind.annotation.XmlType```
- finding concrete classes annotated with ```org.apache.deltaspike.core.api.jmx.MBean```

Because of #38 I cannot check whether this problem has been fixed already in 1.9.12+.

**Comment by lukehutch** [comment] 2016-01-04 23:24
Dangit, I must have broken something, thanks for the report. I'll work on both the bugs you filed within the next day or so.

The unit tests currently pass (otherwise I couldn't push out a release), so that means I need additional unit tests. If you can put together a minimal test case for this bug please, I would appreciate it. (The other bug may be easy enough to figure out without a test case, I'll have to look.)

**Comment by lukehutch** [comment] 2016-01-05 04:58
I did introduce one change recently that causes classes, interfaces and annotations to not be returned/matched unless they are in a whitelisted package prefix (previously, if any class in a whitelisted package *referenced another class*, e.g. using "extends", that class would be returned/matched even if it wasn't itself in a whitelisted package.

If this is not the cause though, it sounds like we'll need to solve #38 first, which will require a specific testcase, since I can't replicate the problem.

**Comment by lukehutch** [comment] 2016-01-05 04:59
PS just in case it somehow solves your problems, please try with the latest release, 1.9.13.

**Comment by lukehutch** [comment] 2016-01-07 05:02
OK, #38 is fixed and checked in (but I haven't pushed out a new release yet), can you please look to see what might be causing #39?

**Comment by lukehutch** [comment] 2016-01-07 05:08
Note that to find annotation `javax.persistence.Entity`, you must have `javax.persistence` in your whitelisted path list. This didn't use to be the case, the whitelist would "spill over" by one link if a class in a non-whitelisted package was referenced by a whitelisted path. I made the whitelisting "hermetic" in 1.9.10, so only classes in whitelisted packages are matched or returned.

I suspect this is the problem you are running into, since all of the annotation types you listed are in third-party packages, but please verify. Meanwhile, I'll update the docs to make this more explicit.

**Comment by lukehutch** [comment] 2016-01-07 05:59
Just released 1.9.14, please try with that version.

**Comment by moldowan** [comment] 2016-01-07 09:07
With 1.9.15 I get:
```java.lang.IllegalArgumentException: Can't scan for javax.jws.WebService, it is in a package that is either blacklisted or not whitelisted```
While this now clearly points to the problem, I find it pretty counterintuitive to include something that I do not want to scan for.

What if ```javax.persistence``` contained a class that is annotated with ```javax.persistence.Entity```?
I guess adding ```javax.persistence``` to ```scanSpec``` would match that class too. This is not what I want and I'm inclined to say that most users would not expect this behaviour.
I my point of view (from a strict user perspective), ```javax.persistence.Entity``` is just a "matcher criteria", not something I want to scan for.

Am I making sense?

**Comment by lukehutch** [comment] 2016-01-07 09:14
Yes, that makes sense. What if you could whitelist class names, not just package names, in the scanning criteria? e.g. `new FastClasspathScanner("com.mypkg", "+javax.persistence.Entity")` -- would this work for you?

**Comment by moldowan** [comment] 2016-01-07 09:23
Well, this would be a workaround.
The major downside of this is that you need to "duplicate" all annotations and classes you use in the the matcher methods. This is especially cumbersome if you add a dynamic number of processors.
Couldn't the scanner just auto-add the classes/annotations from the match-invocations?

Why do you need to "scan" for ```javax.persistence.Entity``` in the first place?
Do you read it's bytecode? If yes, why?

**Comment by lukehutch** [comment] 2016-01-07 09:32
No, the bytecode is not read. It was an intentional change to be clean, since methods like `getNamesOfAllClasses()` / `getNamesOfAllAnnotations()` were returning what could amount to a large number of classes that weren't even whitelisted. Maybe I can just add a method like `.includeReferencedClasses()` to not exclude these.

**Comment by moldowan** [comment] 2016-01-07 10:00
In my opinion the class parameters of the ```match...``` invocations should *not* be included in any of the lists (```getNamesOfAllClasses()``` etc.).
So ```.includeReferencedClasses()``` does not fit 100%.

I wouldn't call those class parameters "referenced" at all.
To be fair, ```javax.persistence.Entity``` is in deed referenced by each entity class but the class parameters are a different thing.

**Closed** 2016-01-07 12:14 UTC

**Comment by lukehutch** [comment] 2016-01-07 12:20
You raise good points -- I implemented this with the semantics you suggested. See [the entry in the docs about this](https://github.com/lukehutch/fast-classpath-scanner#detecting-annotations-superclasses-and-implemented-interfaces-outside-of-whitelisted-packages). I think this will do what you need, but if not, please re-open. Will push out 1.9.16 with this fix.

**Comment by lukehutch** [comment] 2016-01-08 18:49
Does 1.9.16 work as you expect?

**Comment by lukehutch** [comment] 2016-01-16 22:54
I added a couple more fixes for this, let me know if it doesn't work for you. I'll push out 1.9.17 with these fixes.

**Comment by moldowan** [comment] 2016-01-20 10:52
I haven't had the time to test 1.9.16 or .17 yet, but I will do so in the next two weeks or so.

**Comment by lukehutch** [comment] 2016-01-20 11:09
OK, thanks. Skip 1.9.16, it won't work for you, you'll need 1.9.17.
