### ISSUE TITLE
NPE in fastclasspath scanner constructing jBrowserDriver under Scala in sbt test

### ISSUE THREAD

**Issue by MaggieLeber** [lukehutch/fast-classpath-scanner#71] opened 2016-07-29 14:21 UTC
Anybody using fast-classpath-scanner from Scala under `sbt test`? 

see also https://github.com/MachinePublishers/jBrowserDriver/issues/174

```Caused by: java.lang.NullPointerException
        at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:354)
        at java.util.ServiceLoader$LazyIterator.access$600(ServiceLoader.java:323)
        at java.util.ServiceLoader$LazyIterator$1.run(ServiceLoader.java:396)
        at java.util.ServiceLoader$LazyIterator$1.run(ServiceLoader.java:395)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:398)
        at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
        at io.github.lukehutch.fastclasspathscanner.classpath.ClasspathFinder.parseSystemClasspath(ClasspathFinder.java:319)
        at io.github.lukehutch.fastclasspathscanner.classpath.ClasspathFinder.getUniqueClasspathElements(ClasspathFinder.java:375)
        at com.machinepublishers.jbrowserdriver.JBrowserDriver.<clinit>(JBrowserDriver.java:128)
        at common.Common$class.$init$(Common.scala:54)...```

**Comment by lukehutch** [comment] 2016-07-29 23:06
Hi @MaggieLeber, thanks for the report. I'm not sure what caused this, but the `ServiceLoader` framework is gone in the latest release, so you shouldn't see this anymore. Can you please test the latest release (1.93.0) under `sbt test`?

(Don't use git master for now, there's a different issue in the junit tests, introduced last night -- should be fixed by tomorrow.)

**Comment by hollingsworthd** [comment] 2016-07-29 23:41
Via https://github.com/MachinePublishers/jBrowserDriver/issues/174 ... 

Caused by: java.lang.ClassNotFoundException: io.github.lukehutch.fastclasspathscanner.classpath.ClasspathFinder
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.machinepublishers.jbrowserdriver.JBrowserDriver.<clinit>(JBrowserDriver.java:128)

**Comment by lukehutch** [comment] 2016-07-30 05:04
It looks like jBrowserDriver has been updated to the latest FastClasspathScanner API, so I'll close this. Please reopen if you see other issues. Thanks!

**Closed by lukehutch** 2016-07-30 05:04 UTC

**Comment by MaggieLeber** [comment] 2016-07-30 12:40
Yes, thanks for touching base over at jBrowserDriver!
