### ISSUE TITLE
Jar appeared in both some classpath directories and as a classpath entry is not scanned since 1.10.2

### ISSUE THREAD

**Issue by notsyncing** [lukehutch/fast-classpath-scanner#67] opened 2016-07-23 02:45 UTC
Hello, I'm using fast-classpath-scanner for scanning subclasses and annotations in a fat jar, and it works very well.
Recently, I upgraded to version 1.10.4, and found a problem: the jar is ignored from scanning.

jar is mmtshop-web-1.0.0-all.jar, put in location /Users/sfc/Documents/mmtshop/mmtshop-web/build/libs/mmtshop-web-1.0.0-all.jar
classpath contains two entries:
/Users/sfc/Documents/mmtshop/mmtshop-web/build/libs
/Users/sfc/Documents/mmtshop/mmtshop-web/build/libs/mmtshop-web-1.0.0-all.jar

```
--- BEGIN FastClasspathScanner.verbose() LOG ---
2016-07-23T02:14Z	FastClasspathScanner	Found Class-Path entry in jar:file:/Users/sfc/Documents/mmtshop/mmtshop-web/build/libs/mmtshop-web-1.0.0-all.jar!/META-INF/MANIFEST.MF: .
2016-07-23T02:14Z	FastClasspathScanner	Found classpath element: /Users/sfc/Documents/mmtshop/mmtshop-web/build/libs
2016-07-23T02:14Z	FastClasspathScanner	Found classpath element: /Users/sfc/Documents/mmtshop/mmtshop-web/build/libs/mmtshop-web-1.0.0-all.jar
2016-07-23T02:14Z	FastClasspathScanner	Classpath elements from ClassLoader sun.misc.Launcher$AppClassLoader were extracted by ClassLoaderHandler io.github.lukehutch.fastclasspathscanner.classpath.ClasspathFinder$URLClassLoaderHandler
2016-07-23T02:14Z	FastClasspathScanner	Skipping JRE jar: /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Homeq/jre/lib/ext/cldrdata.jar
(...skipped some JRE jars)
2016-07-23T02:14Z	FastClasspathScanner	Skipping JRE jar: /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/ext/zipfs.jar
2016-07-23T02:14Z	FastClasspathScanner	Found classpath element: /System/Library/Java/Extensions/MRJToolkit.jar
2016-07-23T02:14Z	FastClasspathScanner	Classpath elements from ClassLoader sun.misc.Launcher$ExtClassLoader were extracted by ClassLoaderHandler io.github.lukehutch.fastclasspathscanner.classpath.ClasspathFinder$URLClassLoaderHandler
2016-07-23T02:14Z	FastClasspathScanner	Classpath elements: [/Users/sfc/Documents/mmtshop/mmtshop-web/build/libs, /Users/sfc/Documents/mmtshop/mmtshop-web/build/libs/mmtshop-web-1.0.0-all.jar, /System/Library/Java/Extensions/MRJToolkit.jar]
2016-07-23T02:14Z	FastClasspathScanner	Starting scan
2016-07-23T02:14Z	FastClasspathScanner	- Found directory on classpath: /Users/sfc/Documents/mmtshop/mmtshop-web/build/libs
2016-07-23T02:14Z	FastClasspathScanner	--- Scanning directory: /Users/sfc/Documents/mmtshop/mmtshop-web/build/libs
(...skipped some directories...)
2016-07-23T02:14Z	FastClasspathScanner	--- Scanning file: /Users/sfc/Documents/mmtshop/mmtshop-web/build/libs/mmtshop-web-1.0.0-all.jar
2016-07-23T02:14Z	FastClasspathScanner	- Found jar on classpath: /Users/sfc/Documents/mmtshop/mmtshop-web/build/libs/mmtshop-web-1.0.0-all.jar
2016-07-23T02:14Z	FastClasspathScanner	----- Reached duplicate classpath resource, ignoring: file:///Users/sfc/Documents/mmtshop/mmtshop-web/build/libs/mmtshop-web-1.0.0-all.jar
2016-07-23T02:14Z	FastClasspathScanner	- Found jar on classpath: /System/Library/Java/Extensions/MRJToolkit.jar
(...skipped...)
2016-07-23T02:14Z	FastClasspathScanner	- Number of resources scanned: directories: 8; files: 2; jarfiles: 1; jarfile-internal directories: 5; jarfile-internal files: 20
2016-07-23T02:14Z	FastClasspathScanner	Finished .scan() in 0.062474 sec
--- END FastClasspathScanner.verbose() LOG ---
```

From the logs you can see that the scanner found the jar in first classpath entry, but not scanned it inside, then just ignored the second entry.

Downgrade to 1.10.0 doesn't have this problem, from 1.10.2 to latest 1.91.5 the problem persists.

**Comment by lukehutch** [comment] 2016-07-23 03:16
Hi @notsyncing, thanks for this report. Yeah, this doesn't look right :-/  There has been a huge amount of development in the last month though, and it's possible this was fixed already. However, there is a slight API change in the latest release (1.91.5), so you might need to make a small change to your code to use it: the `.scan` method now returns a `ScanResult` object.

Can you please test with 1.91.5 and let me know? I'm trying to get the 2.0 release ready, and I want to make sure this is fixed before then. Thanks!

If 1.91.5 doesn't fix it, is mmtshop-web a jarfile that I can get a copy of? If not, are you able to create a minimal testcase illustrating the problem, please?

(One thing that is strange about this jar is that its META-INF/MANIFEST.MF file contains an entry `Class-Path: .`. Technically Class-Path entries are only really supposed to contain  paths to jarfiles, but it looksl like I need to support this "in-the-wild" case. This is not what is causing your problem though, it's probably something else.)

**Comment by notsyncing** [comment] 2016-07-23 09:18
The problem is not resolved in 1.91.5.
I made a test program:

[test.zip](https://github.com/lukehutch/fast-classpath-scanner/files/379472/test.zip)

This zip contains all code and a built fat jar file in build/libs
You can run the test app with scripts/run.sh (you may need to modify the JAR variable in this script to make it work), because running in IDE doesn't have this problem.
If it runs correctly, it will print ```Found!```; otherwise it will print ```Not found...```

**Comment by notsyncing** [comment] 2016-07-23 09:20
I have forgotten why I added a ```Class-Path: .``` entry in the manifest, but it seems removing it can be a workaround, because the jar will be the first entry in the classpath and get scanned.

**Comment by lukehutch** [comment] 2016-07-23 11:57
Thank you for putting this together, I can reproduce this with FastClasspathScanner 1.9.6. It turns out it's already fixed in my local git repo (for a set of commits I haven't pushed to master yet), for unrelated reasons. 

What was going on was that the `Class-Path: .` entry was causing the directory containing the jar to be scanned recursively, and that was being done before the jar itself was being scanned (which is actually the wrong way around). Then I was using a single set to represent the relative paths of both files and jarfiles already encountered on the classpath, rather than a separate set for each, so once the jar was seen inside `.`, its contents weren't scanned once its own entry was encountered in the classpath.

Anyway, thanks for finding this! For now, go ahead and remove that entry from your jarfile, but it should be fixed in the next release.

(It's actually a bit weird to have `Class-Path: .` in your manifest, because then wherever you place the jarfile becomes a new classpath element root, which is probably not in general a useful thing, and may give unexpected behavior. My opinion is that `Class-Path` manifest entries are in general a really bad design idea on the part of the Java designers.)

**Closed** 2016-07-23 11:57 UTC

**Comment by notsyncing** [comment] 2016-07-24 03:20
Thanks very much!
I have removed the ```Class-Path: .``` entry from the manifest and my program now runs fine.
