### ISSUE TITLE
FCS causing app to fail startup?

### ISSUE THREAD

**Issue by HybridHB** [lukehutch/fast-classpath-scanner#210] opened 2018-07-16 19:02 UTC
Hello, I have a gradle java project and I recently added the latest FCS pacakage via gradle. Simply adding the package and attempting to start my app results in the following.

14:55:06 WARN  Failed startup of context o.a.g.JettyWebAppContext@77d67cf3{/myServer,file:/C:/myServer/build/inplaceWebapp/,STARTING}
java.lang.RuntimeException: Error scanning entry module-info.class from jar file:/C:/Users/myName/.gradle/caches/modules-2/files-2.1/io.github.lukehutch/fast-classpath-scanner/3.1.11/2e6c94d86d465c26b69720619be67340fa4743e8/fast-classpath-scanner-3.1.11.jar
        at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:913) ~[jetty-annotations-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:831) ~[jetty-annotations-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:164) ~[jetty-annotations-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:549) ~[jetty-annotations-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) ~[jetty-util-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) ~[jetty-util-9.2.22.v20170606.jar:9.2.22.v20170606]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
Caused by: java.lang.IllegalArgumentException: null
        at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-5.0.3.jar:5.0.3]
        at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-5.0.3.jar:5.0.3]
        at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-5.0.3.jar:5.0.3]
        at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:973) ~[jetty-annotations-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:956) ~[jetty-annotations-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:909) ~[jetty-annotations-9.2.22.v20170606.jar:9.2.22.v20170606]
        ... 6 common frames omitted

Any idea whats happening? Any help would be appreciated, thanks!

**Comment by lukehutch** [comment] 2018-07-16 19:44
@HybridHB That's actually a pretty weird bug. It doesn't appear that any actual code in FastClasspathScanner is involved in this exception, but I'd still like to get this fixed.

It looks like ObjectWeb ASM doesn't like the `module-info.class` file inside FastClasspathScanner. This file is generated by Moditect, which actually uses ObjectWeb ASM to generate the file, so it's strange that ObjectWeb ASM can't read a file that it actually generated in the first place. @gunnarmorling of Moditect may be able to help you to debug the Moditect side of things -- you should probably even file a bug in the Moditect project: https://github.com/moditect/moditect/issues 

The `IllegalArgumentException: null` error message thrown by ObjectWeb ASM is really unhelpful too, so I also suggest filing a bug there: https://gitlab.ow2.org/asm/asm/issues  Before filing, you should add the source attachment for ObjectWeb ASM to your project, so that you can see method names and line numbers in the stack trace, and then try to set a breakpoint at the line that throws the exception, so that you can see what's going wrong.

It's possible I'm calling Moditect wrong or something, but I have used the FastClasspathScanner module in other projects, so for normal usage, the `module-info.class` file seems to work fine. It just seems to have a problem when being scanned at the bytecode level by ObjectWeb ASM. I think, therefore, that this is a bug in ObjectWeb ASM and/or Moditect.

**Comment by lukehutch** [comment] 2018-07-18 03:42
@HybridHB I can take a look, if you can set up a minimal testcase that reproduces the problem.

**Comment by HybridHB** [comment] 2018-07-19 07:42
Hello, thanks for offering to take a look. Unfortunately I dont have enough time to help look into it further. I had to use another class path scanner to get unblocked. Its possible that its an edge case bug, I was able to get FCS working if I called a static function that uses FCS via a gradle task. But starting the app would cause the issue above. If I have time in the next couple of weeks I can try to setup a repro project, thanks again.

**Comment by lukehutch** [comment] 2018-07-19 10:32
@HybridHB Sorry it didn't work for you. I'll definitely fix the bug if you can show me a simple example of how to get the Jetty AnnotationParser to work in Gradle -- I have no idea how to set that up. Thanks!

**Comment by johnou** [comment] 2018-07-19 10:53
I would recommend upgrading ASM to the latest version before opening the bug report and see if you can still reproduce the problem, 6.2 is out with Java 11 support.

**Comment by lukehutch** [comment] 2018-07-19 11:22
ModiTect uses ASM 6.0 beta so maybe that's the issue. But I suspect that the problem is simply that the Jetty annotation scanner is choking on `module-info.class` files. That's a standard problem with scanners that have not yet been updated.

**Comment by gunnarmorling** [comment] 2018-07-19 11:40
It looks like you're running into this issue
https://github.com/eclipse/jetty.project/issues/1692 which is about Jetty's
annotation parsing not handling JPMS descriptors correctly. This would be
fixed in Jetty 9.4.

**Comment by lukehutch** [comment] 2018-07-19 15:40
Thanks for confirming, @gunnarmorling! Closing.

**Closed by lukehutch** 2018-07-19 15:40 UTC
