### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by sergey-morenets** [lukehutch/fast-classpath-scanner#160] opened 2017-12-01 21:31 UTC
Hi 

I tried to test performance Fast classpath scanner vs Reflections and results seem strange to me. Reflections was 2-7 times faster. Can you please check the benchmark? There were two use cases: find classes with annotations and find classes implementing interface.

```
@Warmup(iterations = 10)
@Measurement(iterations = 10)
@Fork(value = 2, jvmArgsAppend = "-server")
@BenchmarkMode(Mode.Throughput)
@State(Scope.Benchmark)
public class FastClasspathScannerBenchmark {

	@Benchmark
	public void findClassesByAnnotationEntity(Blackhole blackhole) {
		List<Class<?>> classes = new ArrayList<>();
		new FastClasspathScanner("org.project.entity")
				.matchClassesWithAnnotation(Entity.class, classes::add).scan();

		blackhole.consume(classes);
	}

	@Benchmark
	public void findClassesImplementingMyRepositoryInterface(Blackhole blackhole) {
		List<Class<? extends MyRepository>> classes = new ArrayList<>();
		new FastClasspathScanner("org.project.app")
				.matchClassesImplementing(MyRepository.class, classes::add).scan();

		blackhole.consume(classes);
	}

	public static void main(String[] args) throws Exception {
		Options opts = new OptionsBuilder().include(".*").resultFormat(ResultFormatType.TEXT).build();
		new Runner(opts).run();
	}
}
```

```
Benchmark                                                                      Mode  Cnt    Score   Error  Units
FastClasspathScannerBenchmark.findClassesByAnnotationEntity                   thrpt   20   94,983 ± 1,521  ops/s
FastClasspathScannerBenchmark.findClassesImplementingMyRepositoryInterface  thrpt   20   75,718 ± 1,244  ops/s
ReflectionsBenchmark.findClassesByAnnotationEntity                            thrpt   20  658,609 ± 3,943  ops/s
ReflectionsBenchmark.findClassesImplementingMyRepositoryInterface           thrpt   20  177,373 ± 2,174  ops/s

```

**Comment by lukehutch** [comment] 2017-12-03 10:19
@sergey-morenets thanks for reporting this. Generally when there is a discrepancy like this, it is because FCS finds many more jars on the classpath to scan than Reflections (FCS supports more classpath specification mechanisms). However, it's very possible that there was a performance regression too. I'll try to test this soon (I'm currently traveling). In case I can't replicate this problem without running using your exact classpath, could you please turn on verbose logging in both scanners, and attach the results here, so that it's possible to compare the exact set of jars or directories that are scanned in both frameworks? (I assume Reflections has some verbose logging capabilities?)

**Comment by GedMarc** [comment] 2017-12-03 14:23
I've found in large paths with many (many) other-than-class files the scanner does take a knock, with large class path only files it is still quicker (75k+ complex class files).
In JSF or large web-enabled environments there can sometimes be from what I've felt a 7-9 seconds delay when scanning all the html, js, css, minifieds, and other files. It seems as if its the unzip and non-class file scanning.
But I use it extensively, and everywhere. It's doing more (way more) than reflections for me. So I'm not sure with how exactly to approach or even to suggest an improvement. Perhaps only scanning files or directives or extensions placed in the white list? I don't know, but I do know I don't what the functionality gone at all! xD

**Comment by lukehutch** [comment] 2017-12-03 14:42
@gedmarc that's even weirder that FCS is slower than Reflections for non-classfiles (if I understand your comment), since FCS doesn't actually do any processing of non-classfiles, beyond matching the filename, opening the stream, and passing the stream to the user's FileMatchProcessor. Can you please provide an example of timings? PS if you are scanning lots of different things, note that you can do that in a single scanning pass, with multiple MatchProcessors, or multiple queries on the ScanResult.

I'd really like to dig into this performance discrepancy, and fix anything that is wrong. @gedmarc, please also compare the jars/dirs being scanned by

**Comment by sergey-morenets** [comment] 2017-12-03 19:16
Hi @lukehutch 

Thank you for the quick response. I can create sample project with benchmarks and attach it here. So you can test them as well. I also found another interesting point. I tried to test Mechanism 2 vs Mechanism 1 as first one didn't involve class loading and should be generally faster. However benchmarks showed almost no difference:

```
	@Benchmark
	public void findClassesAsStringsByAnnotationEntity(Blackhole blackhole) {
		ScanResult scanResult = new 
				FastClasspathScanner("org.project.entity").scan();

		List<String> classes = scanResult.getNamesOfClassesWithAnnotation(Entity.class);

		blackhole.consume(classes);
	}

	@Benchmark
	public void findClassesByAnnotationEntity(Blackhole blackhole) {
		ScanResult scanResult = new 
				FastClasspathScanner("org.project.entity").scan();

		List<String> classes = scanResult.getNamesOfClassesWithAnnotation(Entity.class);
		
		blackhole.consume(scanResult.classNamesToClassRefs(classes));
	}
```

```
Benchmark                                                                                   Mode  Cnt   Score   Error  Units
FastClasspathScannerBenchmark.findClassesAsStringsByAnnotationEntity                       thrpt   20  98,987 ± 1,489  ops/s
FastClasspathScannerBenchmark.findClassesByAnnotationEntity                                thrpt   20  98,862 ± 1,100  ops/s
```

**Comment by lukehutch** [comment] 2017-12-09 02:55
@sergey-morenets that is interesting indeed. In your example, how many classes actually have the `@Entity` annotation? If the number is small, then the similarity of the benchmarks is not at all surprising. If the number of classes is large, then yes, this is surprising, and it may indicate that classes are being inadvertently loaded.

Unfortunately you can only test for this during the first scan after JVM start, because loaded classes are cached. So you should run the two benchmarks in two separate startups of the JVM, and use a maximally large classpath (with a large number of `@Entity`-annotated classes) each time.

**Comment by GedMarc** [comment] 2017-12-15 09:22
From my side, the slowness is purely zip file size - Lots of js, html and css files extracting and locating causes a lot of overhead. 
Removing all the web files and restricting the black list resolves my issue. This is a bit of a errrgggg with JSF projects where the file count is extremely high.

In a nutshell, must purely be O.S. timing for the delay in processing?

**Comment by sergey-morenets** [comment] 2017-12-15 12:25
Hi

@lukehutch I have no more than 10 @Entity classes. 

@GedMarc Thank you. I will try to follow your suggestions and ignore web resources

**Comment by sergey-morenets** [comment] 2017-12-15 14:05
Hi

@lukehutch I have no more than 10 @Entity classes. 

@GedMarc Thank you. I will try to follow your suggestions and ignore web resources. But how to do that?

If I try to blacklist directories then no @Entity classes are returned:

```
ScanResult scanResult = new FastClasspathScanner("org.project.entity", "-dir:").scan();

List<String> classes = scanResult.getNamesOfClassesWithAnnotation(Entity.class);
```

**Comment by GedMarc** [comment] 2017-12-15 14:21
I went black listing instead of white listing, negative removals as you are correct, I did also experience no custom file finding and etc when specifying white lists. 

You can take a look at https://github.com/GedMarc/GuiceInjection/blob/master/src/za/co/mmagon/guiceinjection/GuiceContext.java for how I do it.

Just to make sure you are running ```scanResult = scanner.scan(); ``` ?

**Comment by lukehutch** [comment] 2017-12-15 22:21
@GedMarc:

* If the main overhead is extracting non-classfiles in your case, then FastClasspathScanner should be dramatically faster than any other scanner, because it creates one `ZipFile` instance per thread (`ZipFile` has a per-thread lock around all operations). Notably, Reflections does not do this. Do you still think that FCS is not extracting these files at the maximum possible speed, and if so, what are you comparing to? If it's not running at the maximum possible speed (limited by IO bandwidth and CPU/VM speed), there's a bug.
* You said "I did also experience no custom file finding and etc when specifying white lists" -- can you please clarify? Whitelisting should work.

@sergey-morenets:

* Can you please confirm that you are not running a separate scan for each entity class? You can do this in a single pass.
* Non-classfiles are ignored by default, unless you use a `FileMatchProcessor`, so they should not be increasing your scan time.
* If specifying "-dir:" doesn't return anything, then that means that what you're trying to match is not stored in a jarfile by the build system, it's in a directory.
* I don't recommend blacklisting everything you don't want to scan, as @GedMarc shows in his code. I recommend whitelisting what you *do* want to scan. That's faster, especially if the classpath grows in size. If whitelisting what you do want to scan is not working for you, it's a bug -- please let me know.
* Can you please confirm what I have requested in previous comments -- I need to know if the slowdown is due to FCS simply finding far more jarfiles on the classpath than Reflections (which is my prediction as to what is happening), rather than FCS being slower at scanning than Reflections (which should not be the case, unless there has been a speed regression). The way to determine this is to run FCS with `.verbose()` to get the logs, which will show the entire classpath that is being scanned. For Reflections, set the slf4j log level to `DEBUG` to show the list of URLs that will be scanned.

Thanks!

**Comment by GedMarc** [comment] 2017-12-15 22:49
I definitely think it is going at maximum speed :) However I am met with a few limitations - 

- I need the scanner to execute asynchronously in EE environments for an ordered execution pattern. In EE7 and under the ForkJoinPools/ThreadLocal's don't tie up properly in wildfly and tomcat, as well as glassfish 4.1 and under. Undertow does not experience this. Due to this I am unable to utilize the asynchronous Zip file loading. This is a known problem to which the only answer given is "it's not a jdk7 function but a jdk8 one" A.k.a. use parallelism from JDK8 in JDK 7 built environments, which is every EE server in existence except Payara 5. For S.E. apps of course this is a non-issue.
- In my testing passthrough's, it is only when loading complete EE apps that a delay is felt. With more than 120k tiny files *average*, and over 20k class files to be scanned in a single low-tier EE app, just the app alone, including the jar files/classpath items not necessary adds a lot of overhead to the app for no particular reason. This is my reasoning behind the black list.
- I have a fixed list of blacklisted libraries that must not be scanned, As a complete utility module, the white list is completely unknown in the scope of scanning. The black list is specified per operating environment using either OSGi mappings or exposed classes (jdk9). Currently this list is fixed static so I can see the complete overall picture before splitting it up into it's separate modules for each applied for EE environment or embedded container.
As an example, in JBoss I want to blacklist a completely different set of libraries to Websphere. But I do not know any package of the application this utility is using.
- I have a strong feeling that the ExecutorService probably needs to be put in place to synchronize the threads properly at read completion phase. .shutdown() and .awaitFinish() are what I'm looking at here to solve this problem. This way I can safely execute the threaded class path reading, in the safety that the operating/container thread will always be joined to the scanning thread at completion with a guaranteed timeout period in whichever environment (JDK7^)

I am very certain the delay is from scanning more items, as well as reading and the time taken to actually unzip large count small file size based applications. When you're looking at a 260MB EAR, with 5 web modules each with their own NPM's and Bower's... and in the knowledge that this is still a small enterprise app, in doing complete testing, the most I've felt is 15 seconds in synchronous (no threads) mode :)

When I'm white listing, specifying a file such as "persistence.xml" or "ejb-jar.xml" it doesn't pass through the zip files finding these files, which I believe is correct and is expected behaviour :) It doesn't bother me too much :)

**Comment by GedMarc** [comment] 2017-12-15 22:53
I definitely think it is going at maximum speed :) However I am met with a few limitations - 

- I need the scanner to execute asynchronously in EE environments for an ordered execution pattern. In EE7 and under the ForkJoinPools/ThreadLocal's don't tie up properly in wildfly and tomcat, as well as glassfish 4.1 and under. Undertow does not experience this. Due to this I am unable to utilize the asynchronous Zip file loading. This is a known problem to which the only answer given is "it's not a jdk7 function but a jdk8 one" A.k.a. use parallelism from JDK8 in JDK 7 built environments, which is every EE server in existence except Payara 5. For S.E. apps of course this is a non-issue.
- In my testing passthrough's, it is only when loading complete EE apps that a delay is felt. With more than 120k tiny files *average*, and over 20k class files to be scanned in a single low-tier EE app, just the app alone, including the jar files/classpath items not necessary adds a lot of overhead to the app for no particular reason. This is my reasoning behind the black list.
- I have a fixed list of blacklisted libraries that must not be scanned, As a complete utility module, the white list is completely unknown in the scope of scanning. The black list is specified per operating environment using either OSGi mappings or exposed classes (jdk9). Currently this list is fixed static so I can see the complete overall picture before splitting it up into it's separate modules for each applied for EE environment or embedded container.
As an example, in JBoss I want to blacklist a completely different set of libraries to Websphere. But I do not know any package of the application this utility is using.
- I have a strong feeling that the ExecutorService probably needs to be put in place to synchronize the threads properly at read completion phase. .shutdown() and .awaitFinish() are what I'm looking at here to solve this problem. This way I can safely execute the threaded class path reading, in the safety that the operating/container thread will always be joined to the scanning thread at completion with a guaranteed timeout period in whichever environment (JDK7^)

I am very certain the delay is from scanning more items, as well as reading and the time taken to actually unzip large count small file size based applications. When you're looking at a 260MB EAR, with 5 web modules each with their own NPM's and Bower's... and in the knowledge that this is still a small enterprise app, in doing complete testing, the most I've felt is 15 seconds in synchronous (no threads) mode :)

When I'm white listing, specifying a file such as "persistence.xml" or "ejb-jar.xml" it doesn't pass through the zip files finding these files, which I believe is correct and is expected behaviour :) It doesn't bother me too much :)
I definitely think it is going at maximum speed :) However I am met with a few limitations - 

- I need the scanner to execute asynchronously in EE environments for an ordered execution pattern. In EE7 and under the ForkJoinPools/ThreadLocal's don't tie up properly in wildfly and tomcat, as well as glassfish 4.1 and under. Undertow does not experience this. Due to this I am unable to utilize the asynchronous Zip file loading. This is a known problem to which the only answer given is "it's not a jdk7 function but a jdk8 one" A.k.a. use parallelism from JDK8 in JDK 7 built environments, which is every EE server in existence except Payara 5. For S.E. apps of course this is a non-issue.
- In my testing passthrough's, it is only when loading complete EE apps that a delay is felt. With more than 120k tiny files *average*, and over 20k class files to be scanned in a single low-tier EE app, just the app alone, including the jar files/classpath items not necessary adds a lot of overhead to the app for no particular reason. This is my reasoning behind the black list.
- I have a fixed list of blacklisted libraries that must not be scanned, As a complete utility module, the white list is completely unknown in the scope of scanning. The black list is specified per operating environment using either OSGi mappings or exposed classes (jdk9). Currently this list is fixed static so I can see the complete overall picture before splitting it up into it's separate modules for each applied for EE environment or embedded container.
As an example, in JBoss I want to blacklist a completely different set of libraries to Websphere. But I do not know any package of the application this utility is using.
- I have a strong feeling that the ExecutorService probably needs to be put in place to synchronize the threads properly at read completion phase. .shutdown() and .awaitFinish() are what I'm looking at here to solve this problem. This way I can safely execute the threaded class path reading, in the safety that the operating/container thread will always be joined to the scanning thread at completion with a guaranteed timeout period in whichever environment (JDK7^)

I am very certain the delay is from scanning more items, as well as reading and the time taken to actually unzip large count small file size based applications. When you're looking at a 260MB EAR, with 5 web modules each with their own NPM's and Bower's... and in the knowledge that this is still a small enterprise app, in doing complete testing, the most I've felt is 15 seconds in synchronous (no threads) mode :)

When I'm white listing, specifying a file such as "persistence.xml" or "ejb-jar.xml" it doesn't pass through the zip files finding these files, which I believe is correct and is expected behaviour :) It doesn't bother me too much :)

**Comment by lukehutch** [comment] 2017-12-15 22:58
@GedMarc this is getting off the topic of @sergey-morenets' original bug report, can you please move this conversation to another bug? Thanks! (Short answer though: FCS has async scanning methods that can use a user-provided execution service -- and FCS does do proper thread syncronization before exit.)  Re. blacklisting, I don't think there's any way to do this other than what you're doing, if you don't know the whitelist ahead of time -- however, you can ask the user to provide a whitelist to your API, and feed that to FCS.

**Comment by lukehutch** [comment] 2017-12-23 11:30
@sergey-morenets please see #162, this may solve your whitelisting problem, if you were trying to scan things in the default package (since you mentioned that whitelisting wasn't working for you as expected).

I'm still curious to hear if you have looked at how many packages are being scanned (and which ones) by FCS compared to Reflections, and whether that explains the scanning speed difference. Thanks!

**Comment by GedMarc** [comment] 2017-12-24 18:13
Whitelisting indeed looks good, Don't hate me but I need to log another one!

**Comment by lukehutch** [comment] 2017-12-24 19:52
@sergey-morenets see let me know if the change in #162 fixes whitelisting for you too.

@GedMarc keep them coming!

**Comment by sergey-morenets** [comment] 2017-12-24 23:30
@lukehutch Thank you. Did you ship new version or provide some patch to update current jar file?

**Comment by lukehutch** [comment] 2017-12-24 23:36
@sergey-morenets there is a new API call checked into the master branch that adds the method `FastClasspathScanner#alwaysScanClasspathElementRoot()`. This will allow you to whitelist the default package (""), without whitelisting all packages in the classpath (because it will scan the default package but not sub-packages, unless the sub-packages are themselves whitelisted). Using this call, you will be able to scan for resources in the root directory of a classpath element. That combined with judicious whitelisting should give you much faster scan times.

I haven't pushed out a new release yet with this change, because @GedMarc indicated that he has another bug or feature request, so I'm waiting to see what that will be. Until then, it would be great if you can build FCS from git master and let me know if this change to whitelisting solves your problem.

PS I'm still interested in a head-to-head comparison between Reflections and FCS for your classpath, so I can see if FCS somehow got slower. Did you ever capture verbose logs from both of them? If so, please attach those here.

**Comment by sergey-morenets** [comment] 2017-12-25 10:16
Hi @lukehutch 

Thank you, I will try to use new version.
I also performed small investigation and it turned out that benchmark results depend on how I run the tests.
If I run benchmarks using IDE(Eclipse or IDEA) then Reflections works much faster. If I run benchmarks using single fat jar(with all the project classes inside) then Fast Classpath Scanner shows better performance. Are these results predictable for you?

```
Command-line(Fat jar)

Benchmark                                                                                   Mode  Cnt    Score   Error  Units
FastClasspathScannerBenchmark.findClassesAsStringsByAnnotationEntity                       thrpt   20  323,120   4,748  ops/s
FastClasspathScannerBenchmark.findClassesAsStringsThatImplementingCityRepositoryInterface  thrpt   20  221,659   4,044  ops/s
FastClasspathScannerBenchmark.findClassesByAnnotationEntity                                thrpt   20  322,773   4,770  ops/s
FastClasspathScannerBenchmark.findClassesThatImplementingCityRepositoryInterface           thrpt   20  221,888   3,754  ops/s
ReflectionsBenchmark.findClassesByAnnotationEntity                                         thrpt   20  275,148   9,588  ops/s
ReflectionsBenchmark.findClassesImplementingCityRepositoryInterface                        thrpt   20  192,976   4,226  ops/s

Eclipse 4.7.2

FastClasspathScannerBenchmark.findClassesAsStringsByAnnotationEntity                       thrpt   20  128,141 ± 1,300  ops/s
FastClasspathScannerBenchmark.findClassesAsStringsThatImplementingCityRepositoryInterface  thrpt   20   93,139 ± 1,544  ops/s
FastClasspathScannerBenchmark.findClassesByAnnotationEntity                                thrpt   20  126,526 ± 3,963  ops/s
FastClasspathScannerBenchmark.findClassesThatImplementingCityRepositoryInterface           thrpt   20   92,317 ± 1,054  ops/s
ReflectionsBenchmark.findClassesByAnnotationEntity                                         thrpt   20  691,535 ± 8,973  ops/s
ReflectionsBenchmark.findClassesImplementingCityRepositoryInterface                        thrpt   20  180,330 ± 1,707  ops/s

InteliJ Idea 2017.3

FastClasspathScannerBenchmark.findClassesAsStringsByAnnotationEntity                       thrpt   20  216,268 ± 4,245  ops/s
FastClasspathScannerBenchmark.findClassesAsStringsThatImplementingCityRepositoryInterface  thrpt   20  123,820 ± 1,443  ops/s
FastClasspathScannerBenchmark.findClassesByAnnotationEntity                                thrpt   20  215,801 ± 3,904  ops/s
FastClasspathScannerBenchmark.findClassesThatImplementingCityRepositoryInterface           thrpt   20  124,436 ± 1,375  ops/s
ReflectionsBenchmark.findClassesByAnnotationEntity                                         thrpt   20  978,293 ± 9,810  ops/s
ReflectionsBenchmark.findClassesImplementingCityRepositoryInterface                        thrpt   20  227,895 ± 2,579  ops/s
```

**Comment by lukehutch** [comment] 2017-12-25 10:24
Again, I cannot will without logs! *Please* attach logs for the two scanners, for each of the runtime environments you describe. I have requested these many times now, and I can't answer in more detail without these. I am confident that the difference comes down to FCS finding more jars to scan than Reflections.

Also, did you try whitelisting packages you want to scan? That should make the scan lightning fast in all runtime environments.

**Comment by sergey-morenets** [comment] 2017-12-25 11:15
Hi @lukehutch 

I attached copy of my project that contains benchmarks Reflections vs Fast Classpath Scanner. You can use it for testing.

Step sequence:
1) Install JDK 9 (or change project settings to JDK 8)
2) Run mvn clean package
3) Run java -jar germes-persistence-1.3.7.jar in the folder germes-persistence/target/
[Fastscanner.zip](https://github.com/lukehutch/fast-classpath-scanner/files/1585770/Fastscanner.zip)

**Comment by lukehutch** [comment] 2017-12-28 06:34
@sergey-morenets I ran the code, with logging enabled, and what I saw was exactly as predicted. Here is the log from Reflections:

```
2017-12-27 22:28:22,905 [main] DEBUG: going to scan these urls:
file:/home/luke/Downloads/germes-fcs/germes-model/target/classes/
2017-12-27 22:28:22,932 [main] INFO : Reflections took 23 ms to scan 1 urls, producing 8 keys and 16 values 
```

This was part of the log from FastClasspathScanner:

```
2017-12-27T22:31:30.932-0700	FastClasspathScanner	-- Final classpath element order:
2017-12-27T22:31:30.932-0700	FastClasspathScanner	---- 0: /home/luke/Downloads/germes-fcs/germes-persistence/target/classes
2017-12-27T22:31:30.933-0700	FastClasspathScanner	---- 1: /home/luke/Downloads/germes-fcs/germes-model/target/classes
2017-12-27T22:31:30.933-0700	FastClasspathScanner	---- 2: /home/luke/.m2/repository/org/hibernate/hibernate-core/5.2.12.Final/hibernate-core-5.2.12.Final.jar
2017-12-27T22:31:30.933-0700	FastClasspathScanner	---- 3: /home/luke/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.jar
2017-12-27T22:31:30.933-0700	FastClasspathScanner	---- 4: /home/luke/.m2/repository/org/jboss/jandex/2.0.3.Final/jandex-2.0.3.Final.jar
2017-12-27T22:31:30.933-0700	FastClasspathScanner	---- 5: /home/luke/.m2/repository/com/fasterxml/classmate/1.3.0/classmate-1.3.0.jar
2017-12-27T22:31:30.933-0700	FastClasspathScanner	---- 6: /home/luke/.m2/repository/org/hibernate/validator/hibernate-validator/6.0.3.Final/hibernate-validator-6.0.3.Final.jar
2017-12-27T22:31:30.933-0700	FastClasspathScanner	---- 7: /home/luke/.m2/repository/javax/validation/validation-api/2.0.0.Final/validation-api-2.0.0.Final.jar
2017-12-27T22:31:30.933-0700	FastClasspathScanner	---- 8: /home/luke/.m2/repository/org/hibernate/common/hibernate-commons-annotations/5.0.0.Final/hibernate-commons-annotations-5.0.0.Final.jar
2017-12-27T22:31:30.933-0700	FastClasspathScanner	---- 9: /home/luke/.m2/repository/org/hibernate/javax/persistence/hibernate-jpa-2.1-api/1.0.0.Final/hibernate-jpa-2.1-api-1.0.0.Final.jar
2017-12-27T22:31:30.933-0700	FastClasspathScanner	---- 10: /home/luke/.m2/repository/org/hibernate/hibernate-entitymanager/5.2.12.Final/hibernate-entitymanager-5.2.12.Final.jar
2017-12-27T22:31:30.933-0700	FastClasspathScanner	---- 11: /home/luke/.m2/repository/org/jboss/logging/jboss-logging/3.3.0.Final/jboss-logging-3.3.0.Final.jar
2017-12-27T22:31:30.933-0700	FastClasspathScanner	---- 12: /home/luke/.m2/repository/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar
2017-12-27T22:31:30.933-0700	FastClasspathScanner	---- 13: /home/luke/.m2/repository/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar
2017-12-27T22:31:30.933-0700	FastClasspathScanner	---- 14: /home/luke/.m2/repository/net/bytebuddy/byte-buddy/1.6.14/byte-buddy-1.6.14.jar
2017-12-27T22:31:30.933-0700	FastClasspathScanner	---- 15: /home/luke/.m2/repository/org/jboss/spec/javax/transaction/jboss-transaction-api_1.2_spec/1.0.1.Final/jboss-transaction-api_1.2_spec-1.0.1.Final.jar
2017-12-27T22:31:30.933-0700	FastClasspathScanner	---- 16: /home/luke/.m2/repository/org/hibernate/hibernate-java8/5.2.12.Final/hibernate-java8-5.2.12.Final.jar
2017-12-27T22:31:30.933-0700	FastClasspathScanner	---- 17: /home/luke/.m2/repository/org/reflections/reflections/0.9.11/reflections-0.9.11.jar
2017-12-27T22:31:30.933-0700	FastClasspathScanner	---- 18: /home/luke/.m2/repository/com/zaxxer/HikariCP/2.6.1/HikariCP-2.6.1.jar
2017-12-27T22:31:30.933-0700	FastClasspathScanner	---- 19: /home/luke/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar
2017-12-27T22:31:30.933-0700	FastClasspathScanner	---- 20: /home/luke/.m2/repository/javax/el/javax.el-api/3.0.0/javax.el-api-3.0.0.jar
2017-12-27T22:31:30.933-0700	FastClasspathScanner	---- 21: /home/luke/.m2/repository/io/github/lukehutch/fast-classpath-scanner/2.9.3/fast-classpath-scanner-2.9.3.jar
2017-12-27T22:31:30.934-0700	FastClasspathScanner	---- 22: /home/luke/.m2/repository/com/google/guava/guava/21.0/guava-21.0.jar
2017-12-27T22:31:30.934-0700	FastClasspathScanner	---- 23: /home/luke/.m2/repository/org/slf4j/slf4j-api/1.7.24/slf4j-api-1.7.24.jar
2017-12-27T22:31:30.934-0700	FastClasspathScanner	---- 24: /home/luke/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.8.1/log4j-slf4j-impl-2.8.1.jar
2017-12-27T22:31:30.934-0700	FastClasspathScanner	---- 25: /home/luke/.m2/repository/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
2017-12-27T22:31:30.934-0700	FastClasspathScanner	---- 26: /home/luke/.m2/repository/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
2017-12-27T22:31:30.934-0700	FastClasspathScanner	---- 27: /home/luke/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
2017-12-27T22:31:30.934-0700	FastClasspathScanner	---- 28: /home/luke/.m2/repository/org/openjdk/jmh/jmh-core/1.19/jmh-core-1.19.jar
2017-12-27T22:31:30.935-0700	FastClasspathScanner	---- 29: /home/luke/.m2/repository/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
2017-12-27T22:31:30.935-0700	FastClasspathScanner	---- 30: /home/luke/.m2/repository/org/apache/commons/commons-math3/3.2/commons-math3-3.2.jar
2017-12-27T22:31:30.935-0700	FastClasspathScanner	---- 31: /home/luke/.m2/repository/org/openjdk/jmh/jmh-generator-annprocess/1.19/jmh-generator-annprocess-1.19.jar
```

Reflections only finds one directory to scan. FCS finds and scans 30 jars and two directories. In fact, Reflections somehow manages to find `germes-model` but not `germes-persistence`, even though both are on the classpath.

The majority of the extra time taken by FCS is in identifying all classpath elements, and getting a directory listing from them.

Here are my benchmark numbers, running in Eclipse: (I just ran the scan directly, since I couldn't get JMH to run in Eclipse):

* 20 calls of `findClassesByAnnotationEntity()` using Reflections: 0.61 sec
* 20 calls of `findClassesAsStringsByAnnotationEntity()` using FCS: 0.48 sec
* 20 calls of `findClassesAsStringsByAnnotationEntity()` using FCS, but calling `.overrideClasspath("/home/luke/Downloads/germes-fcs/germes-model/target/classes/")` (which is the classpath found by Reflections) before calling `.scan()`, so that it's an apples-to-apples comparison: 0.25 sec

If I raise the number of calls to 100, Relfections beats FCS, because there is a thread startup and shutdown cost for FCS that is not incurred by Reflections, but that number of separate scans is unrealistic anyway.

So in the end, in my testing at least, FCS was faster, but it was also scanning 32x the number of classpath elements. If you want your code to be more widely portable, you simply can't rely on Reflections to always find all the things you want to scan in all different types of runtime environments and classloader systems.

However, as you discovered, FCS can sometimes be slower in practice, because it finds many more classpath elements than Reflections. To fix that, you can override the classpath to be scanned, or whitelist or blacklist directories or jars, if you want. Then FCS should always scan faster.

Please let me know if you find any other cases where FCS is clearly scanning the same exact classpath as Reflections more slowly, since that would be a performance bug.

**Comment by lukehutch** [comment] 2017-12-28 06:37
PS for reference, some code to enable log4j logging in Reflections is the following (there is probably a shorter version, I am not a log4j expert, and just copied/pasted this from somewhere). 

```java
ConfigurationBuilder<BuiltConfiguration> builder = ConfigurationBuilderFactory.newConfigurationBuilder();
builder.setStatusLevel(Level.ERROR);
builder.setConfigurationName("BuilderTest");
builder.add(builder.newFilter("ThresholdFilter", Filter.Result.ACCEPT, Filter.Result.NEUTRAL)
		.addAttribute("level", Level.DEBUG));
AppenderComponentBuilder appenderBuilder = builder.newAppender("Stdout", "CONSOLE").addAttribute("target",
		ConsoleAppender.Target.SYSTEM_OUT);
appenderBuilder
		.add(builder.newLayout("PatternLayout").addAttribute("pattern", "%d [%t] %-5level: %msg%n%throwable"));
appenderBuilder.add(builder.newFilter("MarkerFilter", Filter.Result.DENY, Filter.Result.NEUTRAL)
		.addAttribute("marker", "FLOW"));
builder.add(appenderBuilder);
builder.add(builder.newLogger("org.apache.logging.log4j", Level.DEBUG).add(builder.newAppenderRef("Stdout"))
		.addAttribute("additivity", false));
builder.add(builder.newRootLogger(Level.ERROR).add(builder.newAppenderRef("Stdout")));
LoggerContext ctx = Configurator.initialize(builder.build());
```

In FCS, just call `.verbose()` before `.scan()`.

**Comment by lukehutch** [comment] 2017-12-28 06:38
PPS @sergey-morenets please let me know if you think this bug should be closed, given the above information, or if there are more performance issues you want me to look into.

**Comment by sergey-morenets** [comment] 2017-12-28 17:09
Hi @lukehutch 

Thank you for the deep investigation. I think you can close this ticket.

**Comment by lukehutch** [comment] 2017-12-28 20:23
OK, thanks for the report!

**Closed by lukehutch** 2017-12-28 20:23 UTC
