### ISSUE TITLE
Java 9 Jar Issue

### ISSUE THREAD

**Issue by Wafflemon** [lukehutch/fast-classpath-scanner#149] opened 2017-10-24 18:32 UTC
Hello,

So I ran into a bug in this library and the error message said to report the issue here. I think this has to do with the module-info.class that is being added to .jar files by the Java 9 compiler. I haven't even moved to Java 9, but I've been noticing that some of my dependency jars have the module-info.class in them. With the introduction of Jigsaw and the module system, I think they were trying to make it so that Java 9 jars are able to be used as a dependency for Java 8 jars and vice versa. So even in a Java 8 environment, this new module-info.class file is still relevant.

Here is the specific stack trace:
```
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unknown constant pool tag [I@ed6296a in classfile module-info.class (element size unknown, cannot continue reading class. Please report this on the FastClasspathScanner GitHub page.
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1441)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1472)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1495)
	at com.selinc.winchester.paladin.config.adapters.RuntimeConfigAdapterLoader.scanClassPath(RuntimeConfigAdapterLoader.java:168)
	at com.selinc.winchester.paladin.config.adapters.RuntimeConfigAdapterLoader.<init>(RuntimeConfigAdapterLoader.java:51)
	at com.selinc.winchester.paladin.config.adapters.RuntimeConfigAdapterFactory.<init>(RuntimeConfigAdapterFactory.java:47)
	at com.selinc.winchester.paladin.config.adapters.Adapters.configAdapterFactory(Adapters.java:39)
	at com.selinc.winchester.paladin.config.ConfigMarshaller.<clinit>(ConfigMarshaller.java:35)
	... 24 more
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unknown constant pool tag [I@ed6296a in classfile module-info.class (element size unknown, cannot continue reading class. Please report this on the FastClasspathScanner GitHub page.
	at io.github.lukehutch.fastclasspathscanner.utils.InterruptionChecker.executionException(InterruptionChecker.java:74)
	at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue.runWorkLoop(WorkQueue.java:142)
	at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue$1.call(WorkQueue.java:99)
	at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue$1.call(WorkQueue.java:96)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.RuntimeException: Called close() before completing all work units
		at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue.close(WorkQueue.java:194)
		at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:438)
		at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:56)
		... 4 more
Caused by: java.lang.RuntimeException: Unknown constant pool tag [I@ed6296a in classfile module-info.class (element size unknown, cannot continue reading class. Please report this on the FastClasspathScanner GitHub page.
	at io.github.lukehutch.fastclasspathscanner.scanner.ClassfileBinaryParser.readClassInfoFromClassfileHeader(ClassfileBinaryParser.java:561)
	at io.github.lukehutch.fastclasspathscanner.scanner.ClasspathElementZip.openInputStreamAndParseClassfile(ClasspathElementZip.java:347)
	at io.github.lukehutch.fastclasspathscanner.scanner.ClasspathElement.parseClassfiles(ClasspathElement.java:350)
	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner$5.processWorkUnit(Scanner.java:427)
	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner$5.processWorkUnit(Scanner.java:421)
	at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue.runWorkLoop(WorkQueue.java:133)
	... 6 more
```

**Comment by Wafflemon** [comment] 2017-10-24 18:39
I found the Jar that was causing the issue! Here is the maven repository for that dependency.
https://mvnrepository.com/artifact/javax.json.bind/javax.json.bind-api/1.0

**Comment by lukehutch** [comment] 2017-10-24 20:04
@Wafflemon Hi, what version of FCS are you using? I believe this is a dup of #141. I can confirm you are using an old version of FCS, because the reporter of #141 fixed the buggy error message that you were seeing, `Unknown constant pool tag [I@ed6296a` in their PR. Please try upgrading to the latest released version of FCS (2.7.5).

I just tried testing with the maven artifact you linked, and `module-info.class` parses fine with version 2.7.5. So I will close this as fixed, but please comment here to let me know if this version does not fix the issue for you, and I'll reopen. Thanks!

**Closed by lukehutch** 2017-10-24 20:04 UTC

**Comment by Wafflemon** [comment] 2017-10-25 01:36
Oops, I guess I wasn't using the latest version. Thanks for the quick response.

**Comment by lukehutch** [comment] 2017-10-25 08:58
@Wafflemon you're welcome, thanks for the report, and for narrowing down to the jar that was causing the problem!
