### ISSUE TITLE
Problem loading classes with dynamic class loader

### ISSUE THREAD

**Issue by Amooti** [lukehutch/fast-classpath-scanner#94] opened 2016-11-28 07:40 UTC
I'm using a `ClassLoader` extending `URLClassLoader` to dynamically add JAR file urls containing plugin code. I've added this classloader using `FastClasspathScanner#addClassLoader` and am unable to load plugin classes.

The problem seems to be that while the `FastClasspathScanner` does find the correct class names for my plugins, it is unable to create a Class instance in the `FastClasspathScanner#loadClass` method. This method uses `Class#forName` which in turn uses the default class loader instead of the one I've added.

I've also tried using FastClasspathScanner#addClassLoader, but getting the same results. My class loader itself works fine, it is able to load any (both in the plugin JAR and on the class path).

Logging:

```
2016-11-28T08:31:59.707+0100	FastClasspathScanner	FastClasspathScanner version 2.0.8
2016-11-28T08:31:59.911+0100	FastClasspathScanner	Finding classpath entries
2016-11-28T08:31:59.933+0100	FastClasspathScanner	-- ClassLoaderHandlers loaded:
2016-11-28T08:31:59.933+0100	FastClasspathScanner	---- io.github.lukehutch.fastclasspathscanner.classloaderhandler.URLClassLoaderHandler
2016-11-28T08:31:59.933+0100	FastClasspathScanner	---- io.github.lukehutch.fastclasspathscanner.classloaderhandler.EquinoxClassLoaderHandler
2016-11-28T08:31:59.934+0100	FastClasspathScanner	---- io.github.lukehutch.fastclasspathscanner.classloaderhandler.JBossClassLoaderHandler
2016-11-28T08:31:59.934+0100	FastClasspathScanner	---- io.github.lukehutch.fastclasspathscanner.classloaderhandler.WeblogicClassLoaderHandler
2016-11-28T08:31:59.934+0100	FastClasspathScanner	-- Finding classpath elements in ClassLoader company.plugin.PluginClassLoader@33a10788
2016-11-28T08:31:59.934+0100	FastClasspathScanner	---- Adding classpath element: file:/Users/wes/dev/my-project/plugin-loader/target/test-classes/company/plugin/plugin-test-0.1.jar
2016-11-28T08:31:59.948+0100	FastClasspathScanner	-- Scanning jarfile /Users/wes/dev/my-project/plugin-loader/target/test-classes/company/plugin/plugin-test-0.1.jar (took 0.007960 sec)
2016-11-28T08:31:59.951+0100	FastClasspathScanner	---- Found whitelisted file in jarfile: plugin/test/ClassGettingStaticValue.class
2016-11-28T08:31:59.952+0100	FastClasspathScanner	---- Found whitelisted file in jarfile: plugin/test/ClassWithOptional.class
2016-11-28T08:31:59.953+0100	FastClasspathScanner	---- Found whitelisted file in jarfile: plugin/test/ClassWithStream.class
2016-11-28T08:31:59.953+0100	FastClasspathScanner	---- Found whitelisted file in jarfile: plugin/test/ExtendingClass.class
2016-11-28T08:31:59.953+0100	FastClasspathScanner	---- Found whitelisted file in jarfile: plugin/test/ExtendingExternalClass.class
2016-11-28T08:31:59.953+0100	FastClasspathScanner	---- Found whitelisted file in jarfile: plugin/test/ImplementingClass.class
2016-11-28T08:31:59.953+0100	FastClasspathScanner	---- Found whitelisted file in jarfile: plugin/test/ImplementingExternalClass.class
2016-11-28T08:31:59.954+0100	FastClasspathScanner	---- Found whitelisted file in jarfile: plugin/test/SimpleClass.class
2016-11-28T08:31:59.954+0100	FastClasspathScanner	---- Found whitelisted file in jarfile: plugin/test/SomeOtherInterface.class
2016-11-28T08:31:59.954+0100	FastClasspathScanner	---- Found whitelisted file in jarfile: plugin/test/StaticClass.class
2016-11-28T08:31:59.957+0100	FastClasspathScanner	Classpath element order:
2016-11-28T08:31:59.957+0100	FastClasspathScanner	-- 0: /Users/wes/dev/my-project/plugin-loader/target/test-classes/company/plugin/plugin-test-0.1.jar
2016-11-28T08:31:59.999+0100	FastClasspathScanner	Parsing classfile jar:/Users/wes/dev/my-project/plugin-loader/target/test-classes/company/plugin/plugin-test-0.1.jar!plugin/test/ClassGettingStaticValue.class (took 0.001209 sec)
2016-11-28T08:32:00.000+0100	FastClasspathScanner	-- Found class plugin.test.ClassGettingStaticValue
2016-11-28T08:32:00.000+0100	FastClasspathScanner	---- Superclass: java.lang.Object
2016-11-28T08:32:00.000+0100	FastClasspathScanner	Parsing classfile jar:/Users/wes/dev/my-project/plugin-loader/target/test-classes/company/plugin/plugin-test-0.1.jar!plugin/test/ClassWithOptional.class (took 0.000264 sec)
2016-11-28T08:32:00.000+0100	FastClasspathScanner	-- Found class plugin.test.ClassWithOptional
2016-11-28T08:32:00.001+0100	FastClasspathScanner	---- Superclass: java.lang.Object
2016-11-28T08:32:00.001+0100	FastClasspathScanner	Parsing classfile jar:/Users/wes/dev/my-project/plugin-loader/target/test-classes/company/plugin/plugin-test-0.1.jar!plugin/test/ClassWithStream.class (took 0.000245 sec)
2016-11-28T08:32:00.001+0100	FastClasspathScanner	-- Found class plugin.test.ClassWithStream
2016-11-28T08:32:00.001+0100	FastClasspathScanner	---- Superclass: java.lang.Object
2016-11-28T08:32:00.001+0100	FastClasspathScanner	Parsing classfile jar:/Users/wes/dev/my-project/plugin-loader/target/test-classes/company/plugin/plugin-test-0.1.jar!plugin/test/ExtendingClass.class (took 0.000261 sec)
2016-11-28T08:32:00.001+0100	FastClasspathScanner	-- Found class plugin.test.ExtendingClass
2016-11-28T08:32:00.001+0100	FastClasspathScanner	---- Superclass: plugin.test.ImplementingClass
2016-11-28T08:32:00.001+0100	FastClasspathScanner	Parsing classfile jar:/Users/wes/dev/my-project/plugin-loader/target/test-classes/company/plugin/plugin-test-0.1.jar!plugin/test/ExtendingExternalClass.class (took 0.000223 sec)
2016-11-28T08:32:00.001+0100	FastClasspathScanner	-- Found class plugin.test.ExtendingExternalClass
2016-11-28T08:32:00.001+0100	FastClasspathScanner	---- Superclass: company.plugin.testparsers.NormalParser
2016-11-28T08:32:00.002+0100	FastClasspathScanner	Parsing classfile jar:/Users/wes/dev/my-project/plugin-loader/target/test-classes/company/plugin/plugin-test-0.1.jar!plugin/test/ImplementingClass.class (took 0.000733 sec)
2016-11-28T08:32:00.002+0100	FastClasspathScanner	-- Found class plugin.test.ImplementingClass
2016-11-28T08:32:00.002+0100	FastClasspathScanner	---- Superclass: java.lang.Object
2016-11-28T08:32:00.002+0100	FastClasspathScanner	---- Interfaces: plugin.test.SomeOtherInterface
2016-11-28T08:32:00.002+0100	FastClasspathScanner	Parsing classfile jar:/Users/wes/dev/my-project/plugin-loader/target/test-classes/company/plugin/plugin-test-0.1.jar!plugin/test/ImplementingExternalClass.class (took 0.000328 sec)
2016-11-28T08:32:00.003+0100	FastClasspathScanner	-- Found class plugin.test.ImplementingExternalClass
2016-11-28T08:32:00.003+0100	FastClasspathScanner	---- Superclass: java.lang.Object
2016-11-28T08:32:00.003+0100	FastClasspathScanner	---- Interfaces: company.plugin.interfacetest.SomeInterface
2016-11-28T08:32:00.003+0100	FastClasspathScanner	Parsing classfile jar:/Users/wes/dev/my-project/plugin-loader/target/test-classes/company/plugin/plugin-test-0.1.jar!plugin/test/SimpleClass.class (took 0.000244 sec)
2016-11-28T08:32:00.003+0100	FastClasspathScanner	-- Found class plugin.test.SimpleClass
2016-11-28T08:32:00.003+0100	FastClasspathScanner	---- Superclass: java.lang.Object
2016-11-28T08:32:00.003+0100	FastClasspathScanner	Parsing classfile jar:/Users/wes/dev/my-project/plugin-loader/target/test-classes/company/plugin/plugin-test-0.1.jar!plugin/test/SomeOtherInterface.class (took 0.000211 sec)
2016-11-28T08:32:00.003+0100	FastClasspathScanner	-- Found interface class plugin.test.SomeOtherInterface
2016-11-28T08:32:00.003+0100	FastClasspathScanner	---- Superinterface: java.lang.Object
2016-11-28T08:32:00.003+0100	FastClasspathScanner	Parsing classfile jar:/Users/wes/dev/my-project/plugin-loader/target/test-classes/company/plugin/plugin-test-0.1.jar!plugin/test/StaticClass.class (took 0.000235 sec)
2016-11-28T08:32:00.004+0100	FastClasspathScanner	-- Found class plugin.test.StaticClass
2016-11-28T08:32:00.004+0100	FastClasspathScanner	---- Superclass: java.lang.Object
2016-11-28T08:32:00.007+0100	FastClasspathScanner	Building class graph (took 0.009621 sec)
2016-11-28T08:32:00.018+0100	FastClasspathScanner	Calling ClassMatchProcessors
2016-11-28T08:32:00.020+0100	FastClasspathScanner	-- Matched class implementing interface company.plugin.interfacetest.SomeInterface: plugin.test.ImplementingExternalClass
2016-11-28T08:32:00.021+0100	FastClasspathScanner	---- Exception while processing match for class plugin.test.ImplementingExternalClass
2016-11-28T08:32:00.021+0100	FastClasspathScanner	------ java.lang.ClassNotFoundException: plugin.test.ImplementingExternalClass
2016-11-28T08:32:00.021+0100	FastClasspathScanner	------ 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2016-11-28T08:32:00.021+0100	FastClasspathScanner	------ 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2016-11-28T08:32:00.021+0100	FastClasspathScanner	------ 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
2016-11-28T08:32:00.021+0100	FastClasspathScanner	------ 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2016-11-28T08:32:00.021+0100	FastClasspathScanner	------ 	at java.lang.Class.forName0(Native Method)
2016-11-28T08:32:00.021+0100	FastClasspathScanner	------ 	at java.lang.Class.forName(Class.java:264)
2016-11-28T08:32:00.021+0100	FastClasspathScanner	------ 	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec.loadClass(ScanSpec.java:623)
2016-11-28T08:32:00.021+0100	FastClasspathScanner	------ 	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec.access$000(ScanSpec.java:69)
2016-11-28T08:32:00.021+0100	FastClasspathScanner	------ 	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec$7.lookForMatches(ScanSpec.java:973)
2016-11-28T08:32:00.021+0100	FastClasspathScanner	------ 	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec.callMatchProcessors(ScanSpec.java:439)
2016-11-28T08:32:00.021+0100	FastClasspathScanner	------ 	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:365)
2016-11-28T08:32:00.021+0100	FastClasspathScanner	------ 	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:59)
2016-11-28T08:32:00.021+0100	FastClasspathScanner	------ 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2016-11-28T08:32:00.021+0100	FastClasspathScanner	------ 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016-11-28T08:32:00.021+0100	FastClasspathScanner	------ 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016-11-28T08:32:00.021+0100	FastClasspathScanner	------ 	at java.lang.Thread.run(Thread.java:745)
2016-11-28T08:32:00.022+0100	FastClasspathScanner	Completed scan (took 0.106648 sec)
2016-11-28T08:32:00.022+0100	FastClasspathScanner	Number of exceptions raised during classloading and/or while calling MatchProcessors: 1

io.github.lukehutch.fastclasspathscanner.MatchProcessorException: java.lang.ClassNotFoundException: plugin.test.ImplementingExternalClass

	at io.github.lukehutch.fastclasspathscanner.MatchProcessorException.newInstance(MatchProcessorException.java:68)
	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:385)
	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:59)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: plugin.test.ImplementingExternalClass
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec.loadClass(ScanSpec.java:623)
	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec.access$000(ScanSpec.java:69)
	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec$7.lookForMatches(ScanSpec.java:973)
	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec.callMatchProcessors(ScanSpec.java:439)
	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:365)
	... 5 more
```

**Comment by lukehutch** [comment] 2016-11-28 10:38
@Amooti great catch -- I have never used a custom classloader, so I didn't think about this! Please try the change that I just checked in, and let me know if it solves the problem for you.

**Comment by lukehutch** [comment] 2016-11-28 10:56
Update: please try latest change instead.

**Comment by Amooti** [comment] 2016-11-28 12:26
I can confirm that this solves the problem for me. Thanks for the quick reply and fix!

**Comment by lukehutch** [comment] 2016-11-28 17:04
@Amooti great, you're welcome, thanks for testing! Will push out a bugfix release now.

**Comment by lukehutch** [comment] 2016-11-28 17:10
Fixed in 2.0.9.

**Comment by yaitskov** [comment] 2017-01-27 16:31
It looks like I have the same problem in version 2.0.12.
Discovered classes have URLClassLoader 
while rest of application is loaded by jetty WebAppClassLoader.

Bug is not reproducable during running function tests (junit).

I added class loader overriding: 
      .overrideClassLoaders(this.getClass().getClassLoader())

Though It was not enough the class still had different class loader.
Accidentally I noticed that this works:

     discoveredClass.forName(discoveredClass.getName()) 

I have no explanation but result is the same class with jetty classloader.

**Comment by lukehutch** [comment] 2017-01-27 18:42
@yaitskov strange, can you please attach a minimal testcase showing the problem, so that I can replicate it, and also your verbose logs (call `.verbose()` before `.scan()`)?

**Comment by lukehutch** [comment] 2017-01-27 18:48
@yaitskov it is possible WebAppClassLoader is not working yet (I haven't tested it -- if it's not a subclass of URLClassLoader, then it's probably not working yet) -- and tests may use a different classloader.

**Comment by yaitskov** [comment] 2017-01-27 20:06
WebAppClassLoader is a direct descendant of URLClassLoader. It is a Jetty 9. I will check tomorrow when I get back PC.

**Comment by lukehutch** [comment] 2017-01-31 09:12
@yaitskov your bug is probably unrelated to the original issue, since the symptoms are different, but please do test anyway, and please create a new bug report for your issue with a minimal testcase. Thanks!

**Closed by lukehutch** 2017-01-31 09:12 UTC

**Comment by lukehutch** [comment] 2017-02-15 23:24
@yaitskov Just wanted to check -- are you still seeing this issue with the latest release of FCS?
